import { type NextPage } from "next";
import Head from "next/head";
import { Layout } from "src/components/Layout";
import { SproutItem } from "src/components/SproutItem";
import { PlantType, useFindAllPlantsQuery } from "src/generated/graphql";

const Home: NextPage = () => {
  const { data: allPlants } = useFindAllPlantsQuery({
    fetchPolicy: "network-only",
  });

  return (
    <>
      <Head>
        <title>Smart Sprout</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout btn="plus">
        <div className="home-page">
          {allPlants?.findAllPlants.length
            ? allPlants?.findAllPlants.map((plant: PlantType) => (
                <SproutItem key={plant._id} data={plant} />
              ))
            : null}
        </div>
      </Layout>
    </>
  );
};

export default Home;
